/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => YuanYanPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/views/ApprovalView.ts
var import_obsidian3 = require("obsidian");

// src/data.ts
var import_obsidian = require("obsidian");
var YUANYAN_DIR = "\u{1F9E0} \u5143\u6F14\u5FC3\u667A";
var DAILY_INPUT_DIR = `${YUANYAN_DIR}/\u{1F331} \u539F\u6599\u5E93/\u65E5\u8F93\u5165`;
var CAPTURE_DIR = `${YUANYAN_DIR}/\u{1F331} \u539F\u6599\u5E93/\u6355\u83B7`;
var KANBAN_DIR = `${YUANYAN_DIR}/\u2699\uFE0F \u53CD\u54FA\u5F27/\u770B\u677F`;
var PROCESSING_DIR = `${YUANYAN_DIR}/\u{1F33F} \u52A0\u5DE5\u95F4`;
var OUTPUT_ARTICLE_DIR = `${PROCESSING_DIR}/\u6587\u7AE0\u8349\u7A3F`;
var OUTPUT_VIDEO_DIR = `${PROCESSING_DIR}/\u89C6\u9891\u811A\u672C`;
var OUTPUT_TOOL_DIR = `${PROCESSING_DIR}/\u5DE5\u5177\u96CF\u5F62`;
var OUTPUT_EXPLORE_DIR = `${PROCESSING_DIR}/\u653B\u575A`;
var PENDING_FILE = `${KANBAN_DIR}/\u5F85\u5BA1\u6279.json`;
var APPROVAL_LOG_FILE = `${KANBAN_DIR}/\u5BA1\u6279\u65E5\u5FD7.json`;
var CLASSIFY_LOG_FILE = `${KANBAN_DIR}/\u5206\u7C7B\u65E5\u5FD7.json`;
async function readJson(vault, filePath, defaultValue) {
  const normalPath = (0, import_obsidian.normalizePath)(filePath);
  if (await vault.adapter.exists(normalPath)) {
    const content = await vault.adapter.read(normalPath);
    try {
      return JSON.parse(content);
    } catch (e) {
      console.error(`\u5143\u6F14\u5F15\u64CE: JSON \u89E3\u6790\u5931\u8D25 ${normalPath}`);
      return defaultValue;
    }
  }
  return defaultValue;
}
async function writeJson(vault, filePath, data) {
  const normalPath = (0, import_obsidian.normalizePath)(filePath);
  await vault.adapter.write(normalPath, JSON.stringify(data, null, 2));
}
async function readPendingItems(vault) {
  return readJson(vault, PENDING_FILE, []);
}
async function writePendingItems(vault, items) {
  return writeJson(vault, PENDING_FILE, items);
}
async function readApprovalLog(vault) {
  return readJson(vault, APPROVAL_LOG_FILE, []);
}
async function writeApprovalLog(vault, entries) {
  return writeJson(vault, APPROVAL_LOG_FILE, entries);
}
async function writeClassifyLog(vault, entries) {
  return writeJson(vault, CLASSIFY_LOG_FILE, entries);
}
async function readClassifyLog(vault) {
  return readJson(vault, CLASSIFY_LOG_FILE, []);
}
async function appendToApprovalLog(vault, entry) {
  const log = await readApprovalLog(vault);
  log.push(entry);
  await writeApprovalLog(vault, log);
}
async function appendToClassifyLog(vault, entry) {
  const log = await readClassifyLog(vault);
  log.push(entry);
  await writeClassifyLog(vault, log);
}
async function updatePendingItem(vault, itemId, updates) {
  const items = await readPendingItems(vault);
  const idx = items.findIndex((i) => i.id === itemId);
  if (idx === -1)
    return null;
  items[idx] = { ...items[idx], ...updates };
  await writePendingItems(vault, items);
  return items[idx];
}
function isInDailyInputDir(filePath) {
  const normalPath = (0, import_obsidian.normalizePath)(filePath);
  const inputDir = (0, import_obsidian.normalizePath)(DAILY_INPUT_DIR);
  return normalPath.startsWith(inputDir) && normalPath.endsWith(".md");
}
function isInCaptureDir(filePath) {
  const normalPath = (0, import_obsidian.normalizePath)(filePath);
  const captureDir = (0, import_obsidian.normalizePath)(CAPTURE_DIR);
  return normalPath.startsWith(captureDir) && normalPath.endsWith(".md");
}
async function moveFile(vault, sourcePath, targetDir) {
  const sourceNormal = (0, import_obsidian.normalizePath)(sourcePath);
  const fileName = sourceNormal.split("/").pop() || "";
  const baseName = fileName.replace(/\.md$/, "");
  const targetBase = (0, import_obsidian.normalizePath)(`${targetDir}/${fileName}`);
  let targetPath = targetBase;
  let counter = 1;
  while (await vault.adapter.exists((0, import_obsidian.normalizePath)(targetPath))) {
    targetPath = (0, import_obsidian.normalizePath)(`${targetDir}/${baseName}_${counter}.md`);
    counter++;
  }
  try {
    await vault.adapter.rename(sourceNormal, targetPath);
    return targetPath;
  } catch (e) {
    console.error("\u5143\u6F14\u5F15\u64CE: \u6587\u4EF6\u79FB\u52A8\u5931\u8D25", sourceNormal, "\u2192", targetPath, e);
    return null;
  }
}

// src/classifier.ts
async function classifyContent(apiKey, content, fileName, model = "deepseek-chat") {
  var _a, _b, _c;
  const systemPrompt = `\u4F60\u662F\u4E00\u4E2A\u8BA4\u77E5\u5206\u7C7B\u5F15\u64CE\uFF0C\u8D1F\u8D23\u5BF9\u7528\u6237\u7684\u65E5\u8F93\u5165\u5185\u5BB9\u8FDB\u884C\u300C\u5143\u6F14\u5FC3\u667A\u300D\u56DB\u5C42\u5206\u7C7B\u3002

## \u5143\u6F14\u5FC3\u667A\u7CFB\u7EDF\u7B80\u4ECB
\u8FD9\u662F\u4E00\u4E2A\u4E2A\u4EBA\u8BA4\u77E5\u7BA1\u7406\u7CFB\u7EDF\uFF0C\u5E2E\u52A9\u7528\u6237\u628A\u6BCF\u5929\u7684\u60F3\u6CD5\u3001\u5F85\u529E\u3001\u7075\u611F\u8F6C\u5316\u4E3A\u7ED3\u6784\u5316\u77E5\u8BC6\u4EA7\u54C1\u3002

## \u56DB\u5C42\u5206\u7C7B\u6846\u67B6
1. **\u672C\u4F53 (Ontology)** \u2014 \u8FD9\u662F\u4EC0\u4E48\u6027\u8D28\u7684\u5185\u5BB9\uFF1F
   - \u81EA\u6211\u89C9\u5BDF / \u77E5\u8BC6\u5B66\u4E60 / \u95EE\u9898\u89E3\u51B3 / \u7075\u611F\u521B\u610F / \u60C5\u7EEA\u8BB0\u5F55 / \u65E5\u5E38\u4E8B\u52A1 / \u76EE\u6807\u89C4\u5212
2. **\u80FD\u529B (Ability)** \u2014 \u8FD9\u4E2A\u5185\u5BB9\u6D89\u53CA\u4EC0\u4E48\u80FD\u529B\uFF1F
   - \u5143\u8BA4\u77E5 / \u903B\u8F91\u63A8\u7406 / \u77E5\u8BC6\u8FC1\u79FB / \u60C5\u7EEA\u7BA1\u7406 / \u884C\u52A8\u6267\u884C / \u521B\u9020\u529B / \u4FE1\u606F\u6574\u7406
3. **\u89C4\u5219 (Rule)** \u2014 \u4EC0\u4E48\u89C4\u5219/\u539F\u5219\u5728\u8D77\u4F5C\u7528\uFF1F
   - \u7B2C\u4E00\u6027\u539F\u7406 / \u7CFB\u7EDF\u601D\u7EF4 / \u590D\u5229\u6548\u5E94 / \u4E8C\u516B\u6CD5\u5219 / \u5965\u5361\u59C6\u5243\u5200 / \u53CD\u9988\u5FAA\u73AF / \u6CE8\u610F\u529B\u7BA1\u7406
4. **\u4E8B\u4EF6 (Event)** \u2014 \u4EC0\u4E48\u4E8B\u4EF6\u89E6\u53D1\u4E86\u8FD9\u4E2A\u5185\u5BB9\uFF1F
   - \u9605\u8BFB/\u89C2\u5F71 / \u5DE5\u4F5C\u7ECF\u5386 / \u4EBA\u9645\u4EA4\u6D41 / \u81EA\u6211\u53CD\u601D / \u8BA1\u5212\u51B3\u7B56 / \u5916\u90E8\u4FE1\u606F / \u7075\u611F\u95EA\u73B0

## \u4EA7\u51FA\u6807\u7B7E
- **article** \u2014 \u9002\u5408\u5199\u516C\u4F17\u53F7\u6587\u7AE0\uFF08\u6709\u5B8C\u6574\u89C2\u70B9\u3001\u7ED3\u6784\u6E05\u6670\uFF09
- **video** \u2014 \u9002\u5408\u505A\u53E3\u64AD\u89C6\u9891\uFF08\u6709\u6545\u4E8B\u6027\u3001\u9002\u5408\u89C6\u89C9\u8868\u8FBE\uFF09
- **tool** \u2014 \u9002\u5408\u505A\u5DE5\u5177/\u6A21\u677F\uFF08\u6709\u65B9\u6CD5\u8BBA\u3001\u53EF\u64CD\u4F5C\u6027\u5F3A\uFF09
- **explore** \u2014 \u503C\u5F97\u6DF1\u5165\u7814\u7A76\uFF08\u6709\u5F00\u653E\u6027\u3001\u503C\u5F97\u63A2\u7D22\uFF09
- **none** \u2014 \u4E0D\u9002\u5408\u751F\u4EA7\uFF0C\u4EC5\u8BB0\u5F55

## \u8F93\u51FA\u683C\u5F0F
\u5FC5\u987B\u8FD4\u56DE JSON\uFF0C\u683C\u5F0F\u5982\u4E0B\uFF1A
{
  "title": "\u63D0\u70BC\u7684\u6807\u9898",
  "summary": "\u4E00\u53E5\u8BDD\u6458\u8981\uFF0820\u5B57\u5185\uFF09",
  "ontology": "\u672C\u4F53\u5206\u7C7B",
  "ability": "\u80FD\u529B\u5206\u7C7B",
  "rule": "\u89C4\u5219\u5206\u7C7B",
  "event": "\u4E8B\u4EF6\u5206\u7C7B",
  "rationale": "\u5206\u7C7B\u7406\u7531\u7B80\u8FF0",
  "tag": "\u4EA7\u51FA\u6807\u7B7E (article/video/tool/explore/none)"
}`;
  const userPrompt = `\u8BF7\u5BF9\u4EE5\u4E0B\u65E5\u8F93\u5165\u5185\u5BB9\u8FDB\u884C\u5206\u7C7B\uFF1A

\u6587\u4EF6\u540D\uFF1A${fileName}

\u5185\u5BB9\uFF1A
${content}`;
  const requestBody = JSON.stringify({
    model,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.3,
    max_tokens: 2e3
  });
  const https = require("https");
  const responseData = await new Promise((resolve, reject) => {
    let respData = "";
    const req = https.request(
      {
        hostname: "api.deepseek.com",
        path: "/v1/chat/completions",
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`,
          "Content-Length": Buffer.byteLength(requestBody)
        }
      },
      (res) => {
        res.on("data", (chunk) => {
          respData += chunk;
        });
        res.on("end", () => {
          if (res.statusCode !== 200) {
            reject(new Error(`HTTP ${res.statusCode}: ${respData.slice(0, 300)}`));
          } else {
            resolve(respData);
          }
        });
      }
    );
    req.on("error", (e) => {
      reject(new Error(`\u7F51\u7EDC\u8BF7\u6C42\u5931\u8D25: ${e.message}`));
    });
    req.write(requestBody);
    req.end();
  });
  let parsedResponse;
  try {
    parsedResponse = JSON.parse(responseData);
  } catch (e) {
    throw new Error(`JSON\u89E3\u6790\u5931\u8D25: ${responseData.slice(0, 300)}`);
  }
  const replyText = ((_c = (_b = (_a = parsedResponse.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "";
  if (!replyText) {
    throw new Error(`API\u8FD4\u56DE\u7A7A\u5185\u5BB9: ${responseData.slice(0, 300)}`);
  }
  const jsonMatch = replyText.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error(`DeepSeek\u8FD4\u56DE\u683C\u5F0F\u5F02\u5E38: ${replyText.slice(0, 300)}`);
  }
  let parsed;
  try {
    parsed = JSON.parse(jsonMatch[0]);
  } catch (e) {
    throw new Error(`JSON\u89E3\u6790\u5931\u8D25: ${jsonMatch[0].slice(0, 300)}`);
  }
  return {
    title: parsed.title || fileName.replace(/\.md$/, ""),
    summary: parsed.summary || "",
    ontology: parsed.ontology || "\u672A\u5206\u7C7B",
    ability: parsed.ability || "\u672A\u5206\u7C7B",
    rule: parsed.rule || "\u672A\u5206\u7C7B",
    event: parsed.event || "\u672A\u5206\u7C7B",
    rationale: parsed.rationale || "",
    tag: validateTag(parsed.tag)
  };
}
async function generateArticle(apiKey, model, title, sourceContent, summary) {
  const systemPrompt = `\u4F60\u662F\u4E00\u4E2A\u516C\u4F17\u53F7\u6587\u7AE0\u4F5C\u8005\uFF0C\u4E13\u5199\u6709\u6DF1\u5EA6\u3001\u63A5\u5730\u6C14\u7684\u8BA4\u77E5\u63D0\u5347\u7C7B\u6587\u7AE0\u3002

## \u5199\u4F5C\u98CE\u683C
- \u6807\u9898\u6293\u4EBA\uFF0C\u5F00\u5934\u6709\u573A\u666F\u611F\uFF08\u8BA9\u8BFB\u8005\u89C9\u5F97"\u8FD9\u8BF4\u7684\u5C31\u662F\u6211"\uFF09
- \u6B63\u6587\u5206\u5C0F\u6807\u9898\uFF0C\u6BCF\u6BB5300-500\u5B57\uFF0C\u8BED\u8A00\u53E3\u8BED\u5316\u3001\u751F\u52A8
- \u9002\u5F53\u7528\u300C\u4F60\u300D\u6765\u589E\u5F3A\u5BF9\u8BDD\u611F
- \u6709\u5177\u4F53\u6848\u4F8B\u3001\u53EF\u64CD\u4F5C\u7684\u65B9\u6CD5\uFF0C\u4E0D\u7A7A\u8C08
- \u7ED3\u5C3E\u6709\u603B\u7ED3\u5347\u534E + \u4E92\u52A8\u5F15\u5BFC

## \u957F\u5EA6\u8981\u6C42
- \u5168\u6587 1500-2500 \u5B57
- 5-7 \u4E2A\u5C0F\u6807\u9898\u6BB5\u843D
- \u6BCF\u6BB5\u914D\u4E00\u4E2A\u7B80\u77ED\u6848\u4F8B\u6216\u6BD4\u55BB`;
  const userPrompt = `\u8BF7\u6839\u636E\u4EE5\u4E0B\u7D20\u6750\uFF0C\u5199\u4E00\u7BC7\u5B8C\u6574\u7684\u516C\u4F17\u53F7\u6587\u7AE0\u3002

\u539F\u6807\u9898\uFF1A${title}
\u6458\u8981\uFF1A${summary}

\u7D20\u6750\u5185\u5BB9\uFF1A
${sourceContent}

\u8981\u6C42\uFF1A\u76F4\u63A5\u7528\u6587\u7AE0\u6B63\u6587\u8F93\u51FA\uFF0C\u4E0D\u8981 JSON \u5305\u88F9\u3002`;
  const https = require("https");
  const body = JSON.stringify({
    model,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.7,
    max_tokens: 4e3
  });
  return await new Promise((resolve, reject) => {
    const req = https.request({
      hostname: "api.deepseek.com",
      path: "/v1/chat/completions",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
        "Content-Length": Buffer.byteLength(body)
      }
    }, (res) => {
      let data = "";
      res.on("data", (chunk) => {
        data += chunk;
      });
      res.on("end", () => {
        var _a, _b, _c;
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode}`));
          return;
        }
        try {
          const parsed = JSON.parse(data);
          const text = ((_c = (_b = (_a = parsed.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "";
          if (!text)
            reject(new Error("\u8FD4\u56DE\u4E3A\u7A7A"));
          else
            resolve(text);
        } catch (e) {
          reject(new Error(`\u89E3\u6790\u5931\u8D25: ${e.message}`));
        }
      });
    });
    req.on("error", (e) => reject(e.message));
    req.write(body);
    req.end();
  });
}
async function generateScript(apiKey, model, title, sourceContent) {
  const systemPrompt = `\u4F60\u662F\u4E00\u4E2A\u53E3\u64AD\u6587\u6848\u64B0\u7A3F\u4EBA\uFF0C\u64C5\u957F\u628A\u6587\u7AE0\u6539\u6210\u9002\u5408\u53E3\u64AD\u7684\u77ED\u6587\u6848\u3002

## \u683C\u5F0F\u8981\u6C42
- \u5168\u6587\u63A7\u5236\u5728 600-630 \u5B57\u4E4B\u95F4
- \u7528\u77ED\u53E5\uFF0C\u6BCF\u53E5\u8BDD\u5C3D\u91CF\u4E0D\u8D85\u8FC7 20 \u5B57
- \u91CD\u8981\u7684\u89C2\u70B9\u5355\u72EC\u4E00\u884C\uFF0C\u5F62\u6210\u8282\u594F\u611F
- \u9002\u5F53\u4F7F\u7528\u91D1\u53E5\uFF0C\u91D1\u53E5\u524D\u540E\u7559\u7A7A\u884C
- \u4E0D\u7528\u6807\u9898\uFF0C\u4E0D\u7528\u7F16\u53F7\uFF0C\u4ECE\u5934\u5230\u5C3E\u662F\u4E00\u6BB5\u6D41\u7545\u7684\u53E3\u64AD\u7A3F
- \u8BED\u8A00\u53E3\u8BED\u5316\uFF0C\u50CF\u5728\u8DDF\u4E00\u4E2A\u4EBA\u804A\u5929
- \u4E0D\u7528\u914D\u56FE\u8BF4\u660E\uFF0C\u4E0D\u9700\u8981\u5F00\u573A\u767D\u548C\u7ED3\u675F\u8BED

## \u793A\u4F8B\u98CE\u683C
\u597D\u8BBE\u8BA1\u4E0D\u662F\u505A\u52A0\u6CD5\u505A\u5230\u6781\u81F4\u3002
\u662F\u51CF\u5230\u4E0D\u80FD\u518D\u51CF\uFF0C\u8FD8\u80FD\u597D\u770B\u3002
\u5F88\u591A\u9662\u5B50\u4E0D\u662F\u5C0F\uFF0C\u662F\u4E71\u3002
\u4E0D\u662F\u7F3A\u4E1C\u897F\uFF0C\u662F\u4E1C\u897F\u592A\u591A\u3002`;
  const userPrompt = `\u8BF7\u6839\u636E\u4EE5\u4E0B\u6587\u7AE0\u5185\u5BB9\uFF0C\u751F\u6210\u4E00\u6BB5\u53E3\u64AD\u6587\u6848\uFF08600-630\u5B57\uFF09\uFF1A

\u539F\u6807\u9898\uFF1A${title}

\u5185\u5BB9\uFF1A
${sourceContent}

\u8981\u6C42\uFF1A\u77ED\u53E5\u3001\u6362\u884C\u3001\u91D1\u53E5\u3001\u53E3\u8BED\u5316\u3001630\u5B57\u4EE5\u5185\u3002\u76F4\u63A5\u7528\u6587\u6848\u8F93\u51FA\uFF0C\u4E0D\u8981 JSON\u3002`;
  const https = require("https");
  const body = JSON.stringify({
    model,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.7,
    max_tokens: 2e3
  });
  return await new Promise((resolve, reject) => {
    const req = https.request({
      hostname: "api.deepseek.com",
      path: "/v1/chat/completions",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
        "Content-Length": Buffer.byteLength(body)
      }
    }, (res) => {
      let data = "";
      res.on("data", (chunk) => {
        data += chunk;
      });
      res.on("end", () => {
        var _a, _b, _c;
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode}`));
          return;
        }
        try {
          const parsed = JSON.parse(data);
          const text = ((_c = (_b = (_a = parsed.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "";
          if (!text)
            reject(new Error("\u8FD4\u56DE\u4E3A\u7A7A"));
          else
            resolve(text);
        } catch (e) {
          reject(new Error(`\u89E3\u6790\u5931\u8D25: ${e.message}`));
        }
      });
    });
    req.on("error", (e) => reject(e.message));
    req.write(body);
    req.end();
  });
}
function validateTag(tag) {
  const validTags = ["none", "video", "article", "tool", "explore", "publish"];
  if (validTags.includes(tag)) {
    return tag;
  }
  return "none";
}
function tagLabel(tag) {
  const map = {
    none: "\u4E0D\u751F\u4EA7",
    video: "\u89C6\u9891",
    article: "\u6587\u7AE0",
    tool: "\u5DE5\u5177",
    explore: "\u653B\u575A",
    publish: "\u683C\u5F0F\u53D1\u5E03"
  };
  return map[tag] || "\u672A\u77E5";
}
function tagEmoji(tag) {
  const map = {
    none: "\u{1F4CB}",
    video: "\u{1F4F9}",
    article: "\u{1F4DD}",
    tool: "\u{1F527}",
    explore: "\u{1F52C}",
    publish: "\u{1F4E2}"
  };
  return map[tag] || "\u2753";
}

// src/producer.ts
var import_obsidian2 = require("obsidian");
var import_child_process = require("child_process");
var path2 = __toESM(require("path"));

// src/wechat.ts
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var _tokenCache = { token: "", expiresAt: 0 };
async function getAccessToken(appId, appSecret) {
  const now = Date.now() / 1e3;
  if (_tokenCache.token && now < _tokenCache.expiresAt) {
    return _tokenCache.token;
  }
  const https = require("https");
  const url = `https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${appId}&secret=${appSecret}`;
  const data = await new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let d = "";
      res.on("data", (chunk) => d += chunk);
      res.on("end", () => resolve(d));
    }).on("error", (e) => reject(e.message));
  });
  const parsed = JSON.parse(data);
  if (parsed.access_token) {
    _tokenCache = {
      token: parsed.access_token,
      expiresAt: now + parsed.expires_in - 300
    };
    return parsed.access_token;
  }
  throw new Error(`\u5FAE\u4FE1 token \u83B7\u53D6\u5931\u8D25: ${JSON.stringify(parsed)}`);
}
async function uploadWechatImage(appId, appSecret, imagePath) {
  const token = await getAccessToken(appId, appSecret);
  const https = require("https");
  const boundary = "----FormBoundary" + Date.now().toString(36);
  const imgData = fs.readFileSync(imagePath);
  const parts = [
    `--${boundary}\r
Content-Disposition: form-data; name="media"; filename="cover.png"\r
Content-Type: image/png\r
\r
`,
    imgData,
    `\r
--${boundary}--\r
`
  ];
  const body = Buffer.concat(parts.map((p) => Buffer.isBuffer(p) ? p : Buffer.from(p)));
  const urlObj = new URL(
    `https://api.weixin.qq.com/cgi-bin/material/add_material?access_token=${token}&type=image`
  );
  const result = await new Promise((resolve, reject) => {
    const req = https.request(
      {
        hostname: urlObj.hostname,
        path: urlObj.pathname + urlObj.search,
        method: "POST",
        headers: {
          "Content-Type": `multipart/form-data; boundary=${boundary}`,
          "Content-Length": body.length
        }
      },
      (res) => {
        let d = "";
        res.on("data", (c) => d += c);
        res.on("end", () => resolve(d));
      }
    );
    req.on("error", (e) => reject(e.message));
    req.write(body);
    req.end();
  });
  const parsed = JSON.parse(result);
  if (parsed.media_id)
    return parsed.media_id;
  throw new Error(`\u5C01\u9762\u56FE\u7247\u4E0A\u4F20\u5931\u8D25: ${JSON.stringify(parsed)}`);
}
async function uploadWechatInlineImage(appId, appSecret, imagePath) {
  const token = await getAccessToken(appId, appSecret);
  const https = require("https");
  const boundary = "----FormBoundary" + Date.now().toString(36);
  const ext = path.extname(imagePath).toLowerCase() || ".png";
  const mime = ext === ".jpg" || ext === ".jpeg" ? "image/jpeg" : "image/png";
  const imgData = fs.readFileSync(imagePath);
  const parts = [
    `--${boundary}\r
Content-Disposition: form-data; name="media"; filename="img${ext}"\r
Content-Type: ${mime}\r
\r
`,
    imgData,
    `\r
--${boundary}--\r
`
  ];
  const body = Buffer.concat(parts.map((p) => Buffer.isBuffer(p) ? p : Buffer.from(p)));
  const urlObj = new URL(
    `https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=${token}`
  );
  const result = await new Promise((resolve, reject) => {
    const req = https.request(
      {
        hostname: urlObj.hostname,
        path: urlObj.pathname + urlObj.search,
        method: "POST",
        headers: {
          "Content-Type": `multipart/form-data; boundary=${boundary}`,
          "Content-Length": body.length
        }
      },
      (res) => {
        let d = "";
        res.on("data", (c) => d += c);
        res.on("end", () => resolve(d));
      }
    );
    req.on("error", (e) => reject(e.message));
    req.write(body);
    req.end();
  });
  const parsed = JSON.parse(result);
  if (parsed.url)
    return parsed.url;
  throw new Error(`\u6B63\u6587\u56FE\u7247\u4E0A\u4F20\u5931\u8D25: ${JSON.stringify(parsed)}`);
}
async function pushToWechatDraft(appId, appSecret, title, contentMarkdown, thumbMediaId, author = "\u5927\u4E00", digest) {
  try {
    const token = await getAccessToken(appId, appSecret);
    const bodyHtml = `<div class="rich_media_content">${contentMarkdown.replace(/^### (.+)$/gm, "<h3>$1</h3>").replace(/^## (.+)$/gm, "<h2>$1</h2>").replace(/^# (.+)$/gm, "<h1>$1</h1>").replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>").replace(/^- (.+)$/gm, "<li>$1</li>").replace(/\n\n/g, "</p><p>").replace(/\n/g, "<br/>")}</div>`;
    const payload = JSON.stringify({
      articles: [
        {
          title,
          thumb_media_id: thumbMediaId,
          author,
          digest: digest || title,
          content: bodyHtml,
          need_open_comment: 1,
          only_fans_can_comment: 0,
          show_cover_pic: 1
        }
      ]
    });
    const https = require("https");
    const urlObj = new URL(`https://api.weixin.qq.com/cgi-bin/draft/add?access_token=${token}`);
    const result = await new Promise((resolve, reject) => {
      const req = https.request(
        {
          hostname: urlObj.hostname,
          path: urlObj.pathname + urlObj.search,
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Content-Length": Buffer.byteLength(payload)
          }
        },
        (res) => {
          let data = "";
          res.on("data", (chunk) => data += chunk);
          res.on("end", () => resolve(data));
        }
      );
      req.on("error", (e) => reject(e.message));
      req.write(payload);
      req.end();
    });
    const parsed = JSON.parse(result);
    if (parsed.media_id) {
      return parsed.media_id;
    }
    console.error("\u5FAE\u4FE1\u63A8\u9001\u5931\u8D25:", JSON.stringify(parsed));
    return null;
  } catch (e) {
    console.error("\u5FAE\u4FE1\u63A8\u9001\u5F02\u5E38:", e.message);
    return null;
  }
}

// src/producer.ts
async function executeProduction(vault, item, finalTag, ctx) {
  const msg = `[${tagLabel(finalTag)}] ${item.title}`;
  switch (finalTag) {
    case "article":
      await produceArticle(vault, item, ctx);
      break;
    case "publish":
      await produceFormatPublish(vault, item, ctx);
      break;
    case "video":
      await produceVideo(vault, item);
      break;
    case "tool":
      await produceTool(vault, item);
      break;
    case "explore":
      await produceExplore(vault, item);
      break;
    default:
      return `${msg} -> skip`;
  }
  new import_obsidian2.Notice(`Production done: ${msg}`);
  return `${msg} -> done`;
}
function safeName(title) {
  return title.replace(/[<>:"/\\|?*]/g, "_").replace(/\s+/g, "_").slice(0, 60);
}
function frontmatter(item) {
  return `---
title: ${item.title}
source: ${item.sourceFile}
classified: ${item.createdAt}
ontology: ${item.classification.ontology}
ability: ${item.classification.ability}
rule: ${item.classification.rule}
event: ${item.classification.event}
status: full-article
---
`;
}
async function produceFormatPublish(vault, item, ctx) {
  let rawContent = "";
  try {
    const sourcePath = (0, import_obsidian2.normalizePath)(item.sourceFile);
    if (await vault.adapter.exists(sourcePath)) {
      rawContent = await vault.adapter.read(sourcePath);
    }
  } catch (e) {
    rawContent = `# ${item.title}

${item.summary || ""}`;
  }
  const title = item.title || path2.basename(item.sourceFile || "", ".md");
  const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  const outputDir = (0, import_obsidian2.normalizePath)(`${PROCESSING_DIR}/\u5E38\u9A7B`);
  await ensureDir(vault, outputDir);
  const name = safeName(title);
  const images = extractImages(rawContent);
  const imagePaths = resolveImagePaths(images, vault, item.sourceFile);
  if ((ctx == null ? void 0 : ctx.wechatEnabled) && (ctx == null ? void 0 : ctx.wechatAppId) && (ctx == null ? void 0 : ctx.wechatAppSecret)) {
    try {
      let coverMediaId = ctx.wechatCoverMediaId || "";
      if (imagePaths.length > 0 && !coverMediaId) {
        coverMediaId = await uploadWechatImage(
          ctx.wechatAppId,
          ctx.wechatAppSecret,
          imagePaths[0]
        );
      }
      let wechatContent = rawContent;
      const inlineUrls = [];
      for (const imgPath of imagePaths) {
        try {
          const url = await uploadWechatInlineImage(
            ctx.wechatAppId,
            ctx.wechatAppSecret,
            imgPath
          );
          inlineUrls.push(url);
        } catch (e) {
          console.warn("\u56FE\u7247\u4E0A\u4F20\u5931\u8D25\uFF08\u8DF3\u8FC7\uFF09:", imgPath, e.message);
        }
      }
      let imgIdx = 0;
      wechatContent = wechatContent.replace(/!\[\[([^\]]+\.(png|jpg|jpeg|gif|webp))\]\]/gi, () => {
        const url = imgIdx < inlineUrls.length ? inlineUrls[imgIdx++] : "";
        return url ? `<img src="${url}" style="width:100%;margin:16px 0" alt="\u5EAD\u9662\u793A\u610F\u56FE"/>` : "";
      }).replace(/!\[.*?\]\(([^)]+\.(png|jpg|jpeg|gif|webp))\)/gi, () => {
        const url = imgIdx < inlineUrls.length ? inlineUrls[imgIdx++] : "";
        return url ? `<img src="${url}" style="width:100%;margin:16px 0" alt="\u5EAD\u9662\u793A\u610F\u56FE"/>` : "";
      });
      const html = markdownToWechatHtml(wechatContent);
      const mediaId = await pushToWechatDraft(
        ctx.wechatAppId,
        ctx.wechatAppSecret,
        title,
        html,
        coverMediaId,
        "\u5927\u4E00",
        title
      );
      if (mediaId) {
        new import_obsidian2.Notice(`\u516C\u4F17\u53F7\u6587\u7AE0\u5DF2\u63A8\u9001: ${title}`);
      }
    } catch (e) {
      new import_obsidian2.Notice(`\u516C\u4F17\u53F7\u63A8\u9001\u5931\u8D25: ${e.message}`);
    }
  }
  let scriptText = "";
  if (ctx == null ? void 0 : ctx.apiKey) {
    try {
      scriptText = await generateScript(
        ctx.apiKey,
        ctx.model || "deepseek-v4-flash",
        title,
        rawContent
      );
    } catch (e) {
      scriptText = `\uFF08\u53E3\u64AD\u6587\u6848\u751F\u6210\u5931\u8D25: ${e.message}\uFF09`;
    }
  } else {
    scriptText = "\uFF08\u8BF7\u5148\u914D\u7F6E DeepSeek API Key \u4EE5\u751F\u6210\u53E3\u64AD\u6587\u6848\uFF09";
  }
  const scriptPath = (0, import_obsidian2.normalizePath)(`${outputDir}/\u53E3\u64AD-${name}.md`);
  const scriptFm = `---
title: ${title}\uFF08\u53E3\u64AD\u7248\uFF09
created: ${today}
tags: [\u53E3\u64AD, \u811A\u672C]
status: published
words: ${scriptText.length}
source: ${item.sourceFile}
---

`;
  const scriptFull = scriptFm + scriptText + `

---

> \u53E3\u64AD\u6587\u6848 ${scriptText.length} \u5B57\uFF0C\u81EA\u52A8\u751F\u6210\u4E8E ${today}`;
  try {
    await vault.create(scriptPath, scriptFull);
  } catch (e) {
    const ts = Date.now().toString(36);
    await vault.create((0, import_obsidian2.normalizePath)(`${outputDir}/\u53E3\u64AD-${name}_${ts}.md`), scriptFull);
  }
  new import_obsidian2.Notice(`\u53E3\u64AD\u6587\u6848\u5DF2\u4FDD\u5B58\uFF08${scriptText.length}\u5B57\uFF09`);
  const rawFm = `---
title: ${title}
created: ${today}
tags: [publish, \u6574\u7406\u53D1\u5E03]
status: published
source: ${item.sourceFile}
---

`;
  const rawPath = (0, import_obsidian2.normalizePath)(`${outputDir}/\u539F\u6587-${name}.md`);
  try {
    await vault.create(rawPath, rawFm + rawContent);
  } catch (e) {
  }
}
function extractImages(content) {
  const results = [];
  const wikiRe = /!\[\[([^\]]+\.(png|jpg|jpeg|gif|webp))\]\]/gi;
  const mdRe = /!\[.*?\]\(([^)]+\.(png|jpg|jpeg|gif|webp))\)/gi;
  let m;
  while ((m = wikiRe.exec(content)) !== null)
    results.push(m[1]);
  while ((m = mdRe.exec(content)) !== null)
    results.push(m[1]);
  return results;
}
function resolveImagePaths(refs, vault, sourceFile) {
  var _a;
  const results = [];
  const vaultRoot = ((_a = vault.getRoot()) == null ? void 0 : _a.path) || "";
  const sourceDir = path2.dirname(sourceFile);
  for (const ref of refs) {
    const candidates = [
      ref,
      // 原始
      `assets/images/${ref}`,
      // assets/images/
      `${YUANYAN_DIR}/assets/images/${ref}`,
      // 元演心智/assets/images/
      `${sourceDir}/${ref}`,
      // 同目录
      (0, import_obsidian2.normalizePath)(`${vaultRoot}/${ref}`)
      // vault 根
    ];
    results.push((0, import_obsidian2.normalizePath)(candidates[0]));
  }
  return results;
}
function markdownToWechatHtml(md) {
  let text = md.replace(/!\[\[([^\]]+)\]\]/g, "").replace(/!\[.*?\]\(.*?\)/g, "");
  const parts = [];
  const lines = text.split("\n");
  let inBlockquote = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("> ")) {
      if (!inBlockquote) {
        parts.push('<blockquote style="border-left:3px solid #e8753a;padding:10px 16px;margin:12px 0;color:#5a4a3a;background:#f8f4ec;font-size:15px;line-height:1.8">');
        inBlockquote = true;
      }
      parts.push(trimmed.slice(2));
      continue;
    } else if (inBlockquote) {
      parts.push("</blockquote>");
      inBlockquote = false;
    }
    if (!trimmed) {
      parts.push("</p><p style='font-size:15px;line-height:1.9;color:#3a2a1a;margin:10px 0'>");
      continue;
    }
    if (trimmed.startsWith("### ")) {
      parts.push(`<h3 style="font-size:17px;font-weight:700;margin:20px 0 8px;color:#1a1008">${trimmed.slice(4)}</h3>`);
      continue;
    }
    if (trimmed.startsWith("## ")) {
      parts.push(`<h2 style="font-size:19px;font-weight:700;margin:24px 0 8px;color:#1a1008">${trimmed.slice(3)}</h2>`);
      continue;
    }
    if (trimmed.startsWith("# ")) {
      parts.push(`<h1 style="font-size:22px;font-weight:700;margin:24px 0 8px;color:#1a1008">${trimmed.slice(2)}</h1>`);
      continue;
    }
    if (trimmed === "---") {
      parts.push('<hr style="border:0;height:1px;background:#e0d5c8;margin:24px 0">');
      continue;
    }
    let txt = trimmed.replace(/\*\*(.+?)\*\*/g, '<strong style="color:#e8753a">$1</strong>').replace(/__(.+?)__/g, '<strong style="color:#e8753a">$1</strong>');
    parts.push(txt);
  }
  if (inBlockquote)
    parts.push("</blockquote>");
  let html = parts.join("");
  html = `<div class="rich_media_content"><p style="font-size:15px;line-height:1.9;color:#3a2a1a;margin:10px 0">${html}</p></div>`;
  return html;
}
async function produceArticle(vault, item, ctx) {
  let articleBody = "";
  if (ctx == null ? void 0 : ctx.apiKey) {
    try {
      let sourceContent = item.summary;
      try {
        const sourcePath = (0, import_obsidian2.normalizePath)(item.sourceFile);
        if (await vault.adapter.exists(sourcePath)) {
          sourceContent = await vault.adapter.read(sourcePath);
        }
      } catch (e) {
      }
      articleBody = await generateArticle(
        ctx.apiKey,
        ctx.model || "deepseek-v4-flash",
        item.title,
        sourceContent,
        item.summary
      );
    } catch (e) {
      articleBody = `> ${item.summary}

> *(AI generation failed: ${e.message})*

---

## Body

`;
    }
  }
  if (!articleBody) {
    articleBody = `> ${item.summary}

## Body

(To be completed)
`;
  }
  const name = safeName(item.title);
  const filePath = (0, import_obsidian2.normalizePath)(`${OUTPUT_ARTICLE_DIR}/${name}.md`);
  const content = `${frontmatter(item)}${articleBody}

---

*Generated at ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}*
`;
  await ensureDir(vault, OUTPUT_ARTICLE_DIR);
  try {
    await vault.create(filePath, content);
  } catch (e) {
    const ts = Date.now().toString(36);
    await vault.create((0, import_obsidian2.normalizePath)(`${OUTPUT_ARTICLE_DIR}/${name}_${ts}.md`), content);
  }
  if ((ctx == null ? void 0 : ctx.wechatEnabled) && (ctx == null ? void 0 : ctx.wechatAppId) && (ctx == null ? void 0 : ctx.wechatAppSecret) && (ctx == null ? void 0 : ctx.wechatCoverMediaId)) {
    try {
      const mediaId = await pushToWechatDraft(
        ctx.wechatAppId,
        ctx.wechatAppSecret,
        item.title,
        articleBody,
        ctx.wechatCoverMediaId,
        "\u5927\u4E00",
        item.summary || item.title
      );
      if (mediaId)
        new import_obsidian2.Notice(`WeChat draft pushed: ${mediaId.slice(0, 10)}...`);
      else
        new import_obsidian2.Notice(`WeChat push failed, check console`);
    } catch (e) {
      new import_obsidian2.Notice(`WeChat push error: ${e.message}`);
    }
  }
}
async function produceVideo(vault, item) {
  const name = safeName(item.title);
  const filePath = (0, import_obsidian2.normalizePath)(`${OUTPUT_VIDEO_DIR}/${name}.md`);
  const content = `${frontmatter(item)}# Video script: ${item.title}

Source: [[${item.sourceFile.replace(/\.md$/, "")}]]

## Core idea
${item.summary}

## Script

(To be completed)
`;
  await ensureDir(vault, OUTPUT_VIDEO_DIR);
  try {
    await vault.create(filePath, content);
  } catch (e) {
    await vault.create((0, import_obsidian2.normalizePath)(`${OUTPUT_VIDEO_DIR}/${name}_${Date.now().toString(36)}.md`), content);
  }
}
async function produceTool(vault, item) {
  const name = safeName(item.title);
  const filePath = (0, import_obsidian2.normalizePath)(`${OUTPUT_TOOL_DIR}/${name}.md`);
  const content = `${frontmatter(item)}# Tool: ${item.title}

Background: ${item.classification.rationale}
`;
  await ensureDir(vault, OUTPUT_TOOL_DIR);
  try {
    await vault.create(filePath, content);
  } catch (e) {
    await vault.create((0, import_obsidian2.normalizePath)(`${OUTPUT_TOOL_DIR}/${name}_${Date.now().toString(36)}.md`), content);
  }
}
async function produceExplore(vault, item) {
  const name = safeName(item.title);
  const filePath = (0, import_obsidian2.normalizePath)(`${OUTPUT_EXPLORE_DIR}/${name}.md`);
  const content = `${frontmatter(item)}# Explore: ${item.title}

Source: [[${item.sourceFile.replace(/\.md$/, "")}]]

## Questions

1.
2.
`;
  await ensureDir(vault, OUTPUT_EXPLORE_DIR);
  try {
    await vault.create(filePath, content);
  } catch (e) {
    await vault.create((0, import_obsidian2.normalizePath)(`${OUTPUT_EXPLORE_DIR}/${name}_${Date.now().toString(36)}.md`), content);
  }
}
async function ensureDir(vault, dirPath) {
  const normalPath = (0, import_obsidian2.normalizePath)(dirPath);
  if (!await vault.adapter.exists(normalPath)) {
    await vault.adapter.mkdir(normalPath);
  }
}

// src/views/ApprovalView.ts
var APPROVAL_VIEW_TYPE = "yuanyan-approval";
var ApprovalView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return APPROVAL_VIEW_TYPE;
  }
  getDisplayText() {
    return "Yuanyan Approval";
  }
  getIcon() {
    return "check-check";
  }
  async onload() {
    super.onload();
    this.contentEl.empty();
    this.contentEl.addClass("yuanyan-approval-view");
    await this.render();
  }
  async render() {
    this.contentEl.empty();
    const h = this.contentEl.createEl("div", { cls: "yuanyan-header" });
    h.createEl("h2", { text: "\u5143\u6F14\u5F15\u64CE \xB7 \u5BA1\u6279\u9762\u677F" });
    const items = await readPendingItems(this.plugin.app.vault);
    const pending = items.filter((i) => i.status === "pending");
    const processed = items.filter((i) => i.status !== "pending");
    if (pending.length === 0) {
      this.contentEl.createEl("div", { cls: "yuanyan-empty" }).createSpan({ text: "\u6682\u65E0\u5F85\u5BA1\u6279\u9879" });
    } else {
      const sec = this.contentEl.createEl("div", { cls: "yuanyan-section" });
      sec.createEl("h3", { text: `\u5F85\u5BA1\u6279 (${pending.length})` });
      for (const item of pending) {
        const card = sec.createEl("div", { cls: "yuanyan-card" });
        this.renderCard(card, item);
      }
    }
    if (processed.length > 0) {
      const sec = this.contentEl.createEl("div", { cls: "yuanyan-section" });
      sec.createEl("h3", { text: `\u5DF2\u5904\u7406 (${processed.length})` });
      for (const item of processed.slice(0, 10)) {
        sec.createEl("div", { cls: "yuanyan-processed-entry" }).setText(
          item.title + (item.finalTag ? ` ${tagEmoji(item.finalTag)}` : "")
        );
      }
    }
  }
  renderCard(container, item) {
    var _a;
    container.createEl("div", { text: item.title, cls: "yuanyan-card-title" });
    if (item.summary)
      container.createEl("div", { text: item.summary, cls: "yuanyan-card-summary" });
    if ((_a = item.classification) == null ? void 0 : _a.rationale) {
      container.createEl("div", {
        text: `[${tagLabel(item.suggestedTag)}] ${item.classification.rationale}`,
        cls: "yuanyan-card-rationale"
      });
    }
    const actions = container.createEl("div", { cls: "yuanyan-actions" });
    this.addBtn(actions, "\u2705 \u901A\u8FC7", async () => this.approveItem(item, item.suggestedTag));
    this.addBtn(actions, "\u274C \u62D2\u7EDD", async () => this.rejectItem(item));
    this.addBtn(actions, "\u{1F4F9} \u89C6\u9891", async () => this.approveItem(item, "video"));
    this.addBtn(actions, "\u{1F4DD} \u6587\u7AE0", async () => this.approveItem(item, "article"));
    this.addBtn(actions, "\u{1F527} \u5DE5\u5177", async () => this.approveItem(item, "tool"));
    this.addBtn(actions, "\u{1F4E2} \u683C\u5F0F\u53D1\u5E03", async () => this.approveItem(item, "publish"), "#5a8e6a");
  }
  addBtn(container, label, onClick, color) {
    const btn = container.createEl("button", { cls: "yuanyan-btn-approve" });
    btn.setText(label);
    if (color)
      btn.style.borderColor = color;
    btn.onclick = async () => {
      btn.setAttr("disabled", "true");
      btn.setText("...");
      try {
        await onClick();
      } catch (e) {
        new import_obsidian3.Notice(`Error: ${e.message}`);
        btn.removeAttribute("disabled");
        btn.setText(label);
      }
    };
  }
  async approveItem(item, finalTag) {
    const action = finalTag === "publish" ? "publish" : finalTag === item.suggestedTag ? "approve" : "convert";
    await appendToApprovalLog(this.plugin.app.vault, {
      id: crypto.randomUUID(),
      itemId: item.id,
      sourceFile: item.sourceFile,
      action,
      originalTag: item.suggestedTag,
      finalTag,
      timestamp: (/* @__PURE__ */ new Date()).toISOString()
    });
    await executeProduction(this.plugin.app.vault, item, finalTag, {
      apiKey: this.plugin.settings.deepseekApiKey,
      model: this.plugin.settings.deepseekModel,
      wechatAppId: this.plugin.settings.wechatAppId,
      wechatAppSecret: this.plugin.settings.wechatAppSecret,
      wechatEnabled: this.plugin.settings.wechatEnabled,
      wechatCoverMediaId: this.plugin.settings.wechatCoverMediaId
    });
    await updatePendingItem(this.plugin.app.vault, item.id, {
      status: "approved",
      approvedAt: (/* @__PURE__ */ new Date()).toISOString(),
      finalTag
    });
    await this.render();
  }
  async rejectItem(item) {
    await appendToApprovalLog(this.plugin.app.vault, {
      id: crypto.randomUUID(),
      itemId: item.id,
      sourceFile: item.sourceFile,
      action: "reject",
      originalTag: item.suggestedTag,
      finalTag: "none",
      timestamp: (/* @__PURE__ */ new Date()).toISOString()
    });
    await updatePendingItem(this.plugin.app.vault, item.id, {
      status: "rejected",
      approvedAt: (/* @__PURE__ */ new Date()).toISOString(),
      finalTag: "none"
    });
    new import_obsidian3.Notice(`Rejected: ${item.title}`);
    await this.render();
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var DEFAULT_SETTINGS = {
  deepseekApiKey: "",
  deepseekModel: "deepseek-chat",
  enabled: true,
  wechatAppId: "",
  wechatAppSecret: "",
  wechatEnabled: false,
  wechatCoverMediaId: "",
  flomoApiKey: "",
  flomoSyncEnabled: false
};
var YuanYanSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5143\u6F14\u5F15\u64CE\u8BBE\u7F6E" });
    new import_obsidian4.Setting(containerEl).setName("\u542F\u7528\u5F15\u64CE").setDesc("\u5F00\u542F/\u5173\u95ED\u81EA\u52A8\u5206\u7C7B\u548C\u751F\u4EA7\u529F\u80FD").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "DeepSeek API \u914D\u7F6E" });
    new import_obsidian4.Setting(containerEl).setName("API Key").setDesc("\u7528\u4E8E\u5206\u7C7B\u548C\u6587\u7AE0\u751F\u6210\u7684 DeepSeek API \u5BC6\u94A5").addText(
      (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.deepseekApiKey).onChange(async (value) => {
        this.plugin.settings.deepseekApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u6A21\u578B\u540D\u79F0\uFF0C\u5982 deepseek-v4-flash").addText(
      (text) => text.setPlaceholder("deepseek-v4-flash").setValue(this.plugin.settings.deepseekModel).onChange(async (value) => {
        this.plugin.settings.deepseekModel = value.trim() || "deepseek-v4-flash";
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u5FAE\u4FE1\u516C\u4F17\u53F7\u914D\u7F6E" });
    new import_obsidian4.Setting(containerEl).setName("\u542F\u7528\u516C\u4F17\u53F7\u63A8\u9001").setDesc("\u5BA1\u6279\u901A\u8FC7\u6587\u7AE0\u540E\u81EA\u52A8\u63A8\u9001\u5230\u516C\u4F17\u53F7\u8349\u7A3F\u7BB1").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.wechatEnabled).onChange(async (value) => {
        this.plugin.settings.wechatEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("AppID").setDesc("\u516C\u4F17\u53F7\u5F00\u53D1\u4FE1\u606F\u4E2D\u7684 AppID").addText(
      (text) => text.setPlaceholder("wx...").setValue(this.plugin.settings.wechatAppId).onChange(async (value) => {
        this.plugin.settings.wechatAppId = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("AppSecret").setDesc("\u516C\u4F17\u53F7\u5F00\u53D1\u4FE1\u606F\u4E2D\u7684 AppSecret").addText(
      (text) => text.setPlaceholder("...").setValue(this.plugin.settings.wechatAppSecret).onChange(async (value) => {
        this.plugin.settings.wechatAppSecret = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Flomo \u540C\u6B65\u914D\u7F6E" });
    new import_obsidian4.Setting(containerEl).setName("\u542F\u7528 Flomo \u540C\u6B65").setDesc("\u5B9A\u65F6\u4ECE Flomo \u62C9\u53D6\u7B14\u8BB0\u5230\u6355\u83B7\u76EE\u5F55").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.flomoSyncEnabled).onChange(async (value) => {
        this.plugin.settings.flomoSyncEnabled = value;
        await this.plugin.saveSettings();
        if (value) {
          this.plugin.startFlomoSync();
        } else {
          this.plugin.stopFlomoSync();
        }
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Flomo API Key").setDesc("Flomo Pro \u7528\u6237\u7684 API \u5BC6\u94A5\uFF08\u8BBE\u7F6E \u2192 API \u2192 \u590D\u5236\uFF09").addText(
      (text) => text.setPlaceholder("\u8F93\u5165 Flomo API Key").setValue(this.plugin.settings.flomoApiKey).onChange(async (value) => {
        this.plugin.settings.flomoApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u7ACB\u5373\u540C\u6B65").setDesc("\u624B\u52A8\u89E6\u53D1\u4E00\u6B21 Flomo \u7B14\u8BB0\u540C\u6B65").addButton(
      (button) => button.setButtonText("\u{1F504} \u540C\u6B65").setCta().onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("\u540C\u6B65\u4E2D...");
        await this.plugin.triggerFlomoSync();
        button.setButtonText("\u2705 \u5B8C\u6210");
        setTimeout(() => {
          button.setButtonText("\u{1F504} \u540C\u6B65");
          button.setDisabled(false);
        }, 2e3);
      })
    );
  }
};

// src/main.ts
var PROCESSED_FILES_KEY = "processedFiles";
var FlomoConfirmModal = class extends import_obsidian5.Modal {
  constructor(app, plugin, filePath, title, preview, onConfirm, onDecline) {
    super(app);
    this.plugin = plugin;
    this.filePath = filePath;
    this.title = title;
    this.preview = preview;
    this.onConfirm = onConfirm;
    this.onDecline = onDecline;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("flomo-confirm-modal");
    contentEl.createEl("h2", { text: "\u{1F4EE} \u68C0\u6D4B\u5230 Flomo \u65B0\u7B14\u8BB0" });
    contentEl.createEl("h3", { text: this.title, cls: "flomo-note-title" });
    const previewEl = contentEl.createEl("div", { cls: "flomo-preview" });
    previewEl.createEl("p", { text: this.preview.slice(0, 200) });
    if (this.preview.length > 200) {
      previewEl.createEl("p", { text: "......", cls: "flomo-preview-more" });
    }
    new import_obsidian5.Setting(contentEl).addButton(
      (button) => button.setButtonText("\u274C \u7559\u5728\u6355\u83B7").setWarning().onClick(() => {
        this.close();
        this.onDecline();
      })
    ).addButton(
      (button) => button.setButtonText("\u2705 \u79FB\u5165\u65E5\u8F93\u5165").setCta().onClick(() => {
        this.close();
        this.onConfirm();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var YuanYanPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.engineStatus = "idle";
    this.processedFiles = /* @__PURE__ */ new Set();
    this.debounceTimer = null;
    this.pendingChanges = /* @__PURE__ */ new Map();
    // ── 新增 Flomo 相关 ──
    this.declinedFiles = /* @__PURE__ */ new Set();
    this.flomoCheckTimer = null;
  }
  async onload() {
    await this.loadSettings();
    await this.loadProcessedState();
    await this.loadDeclinedState();
    this.registerView(APPROVAL_VIEW_TYPE, (leaf) => new ApprovalView(leaf, this));
    const ribbonIcon = this.addRibbonIcon("list-checks", "\u5143\u6F14\u5F15\u64CE \xB7 \u5BA1\u6279\u9762\u677F", async () => {
      await this.openApprovalView();
    });
    ribbonIcon.addClass("yuanyan-ribbon-icon");
    this.addCommand({
      id: "open-approval-panel",
      name: "\u6253\u5F00\u5BA1\u6279\u9762\u677F",
      callback: async () => {
        await this.openApprovalView();
      }
    });
    this.addCommand({
      id: "classify-unprocessed",
      name: "\u5206\u7C7B\u672A\u5904\u7406\u7684\u65E5\u8F93\u5165",
      callback: async () => {
        await this.processExistingFiles();
        new import_obsidian5.Notice("\u5143\u6F14\u5F15\u64CE: \u5206\u7C7B\u5B8C\u6210");
      }
    });
    this.addCommand({
      id: "format-publish",
      name: "\u683C\u5F0F\u5316\u53D1\u5E03\u65E5\u8F93\u5165 \u2192 \u516C\u4F17\u53F7\uFF08\u8DF3\u8FC7 AI \u5BA1\u6279\uFF09",
      callback: async () => {
        await this.quickFormatPublish();
      }
    });
    this.addCommand({
      id: "test-api-debug",
      name: "1. \u6D4B\u8BD5 API \u8FDE\u63A5\uFF08\u8C03\u8BD5\u7528\uFF09",
      callback: async () => {
        await this.testApiConnection();
      }
    });
    this.addCommand({
      id: "show-plugin-state",
      name: "2. \u67E5\u770B\u63D2\u4EF6\u72B6\u6001\uFF08\u8C03\u8BD5\u7528\uFF09",
      callback: async () => {
        await this.showState();
      }
    });
    this.addSettingTab(new YuanYanSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian5.TFile)
          this.onFileChange(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian5.TFile)
          this.onFileChange(file);
      })
    );
    if (this.settings.enabled && this.settings.deepseekApiKey) {
      this.engineStatus = "running";
      setTimeout(() => this.processExistingFiles(), 3e3);
      if (this.settings.flomoSyncEnabled) {
        this.startFlomoCaptureWatch();
      }
    }
  }
  onunload() {
    console.log("\u5143\u6F14\u5F15\u64CE: \u63D2\u4EF6\u5378\u8F7D");
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadProcessedState() {
    const data = await this.loadData();
    if (data == null ? void 0 : data[PROCESSED_FILES_KEY]) {
      this.processedFiles = new Set(data[PROCESSED_FILES_KEY]);
    }
  }
  async saveProcessedState() {
    const data = await this.loadData() || {};
    data[PROCESSED_FILES_KEY] = Array.from(this.processedFiles);
    await this.saveData(data);
  }
  // ========== 快捷格式化发布（跳过 AI 审批） ==========
  async quickFormatPublish() {
    if (!this.settings.wechatEnabled || !this.settings.wechatAppId || !this.settings.wechatAppSecret) {
      new import_obsidian5.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E\u516C\u4F17\u53F7\u4FE1\u606F\uFF08AppID + AppSecret\uFF09");
      return;
    }
    const inputDir = (0, import_obsidian5.normalizePath)(DAILY_INPUT_DIR);
    if (!await this.app.vault.adapter.exists(inputDir)) {
      new import_obsidian5.Notice("\u65E5\u8F93\u5165\u76EE\u5F55\u4E0D\u5B58\u5728");
      return;
    }
    const files = this.app.vault.getFiles().filter(
      (f) => isInDailyInputDir(f.path) && !this.processedFiles.has(f.path)
    );
    if (files.length === 0) {
      new import_obsidian5.Notice("\u6CA1\u6709\u672A\u5904\u7406\u7684\u65E5\u8F93\u5165\u6587\u4EF6");
      return;
    }
    new import_obsidian5.Notice(`\u6B63\u5728\u683C\u5F0F\u5316\u53D1\u5E03 ${files.length} \u4E2A\u6587\u4EF6...`);
    for (const file of files) {
      try {
        const content = await this.app.vault.read(file);
        if (!content.trim())
          continue;
        const title = file.name.replace(/\.md$/, "");
        const itemId = `yy-pub-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
        const pendingItems = await readPendingItems(this.app.vault);
        const newItem = {
          id: itemId,
          sourceFile: file.path,
          title,
          summary: "",
          classification: { ontology: "\u65E5\u5E38\u8F93\u51FA", ability: "\u5199\u4F5C", rule: "\u77E5\u884C\u5408\u4E00", event: "\u521B\u4F5C", rationale: "\u683C\u5F0F\u5316\u53D1\u5E03" },
          suggestedTag: "publish",
          status: "pending",
          createdAt: (/* @__PURE__ */ new Date()).toISOString()
        };
        pendingItems.unshift(newItem);
        await writePendingItems(this.app.vault, pendingItems);
        await executeProduction(this.app.vault, newItem, "publish", {
          apiKey: this.settings.deepseekApiKey,
          model: this.settings.deepseekModel,
          wechatAppId: this.settings.wechatAppId,
          wechatAppSecret: this.settings.wechatAppSecret,
          wechatEnabled: this.settings.wechatEnabled,
          wechatCoverMediaId: this.settings.wechatCoverMediaId || ""
        });
        this.processedFiles.add(file.path);
        await this.saveProcessedState();
      } catch (e) {
        new import_obsidian5.Notice(`\u300C${file.name}\u300D\u53D1\u5E03\u5931\u8D25: ${e.message}`);
      }
    }
    new import_obsidian5.Notice("\u683C\u5F0F\u5316\u53D1\u5E03\u5B8C\u6210");
    this.refreshApprovalView();
  }
  async showState() {
    const data = await this.loadData();
    const msg = `\u542F\u7528: ${this.settings.enabled}
API Key: ${this.settings.deepseekApiKey ? this.settings.deepseekApiKey.slice(0, 10) + "..." : "\u672A\u8BBE\u7F6E"}
\u6A21\u578B: ${this.settings.deepseekModel}
\u72B6\u6001: ${this.engineStatus}
\u5DF2\u5904\u7406\u6587\u4EF6: ${this.processedFiles.size}\u4E2A`;
    new import_obsidian5.Notice(msg, 8e3);
  }
  async testApiConnection() {
    if (!this.settings.deepseekApiKey) {
      new import_obsidian5.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Key");
      return;
    }
    try {
      const files = this.app.vault.getFiles().filter((f) => isInDailyInputDir(f.path));
      if (files.length === 0) {
        new import_obsidian5.Notice("\u672A\u627E\u5230\u65E5\u8F93\u5165\u6587\u4EF6");
        return;
      }
      const file = files[0];
      const content = await this.app.vault.read(file);
      const https = require("https");
      const systemPrompt = `\u4F60\u662F\u4E00\u4E2A\u5206\u7C7B\u5F15\u64CE\u3002\u8BF7\u5BF9\u4EE5\u4E0B\u65E5\u8F93\u5165\u5185\u5BB9\u8FDB\u884C\u56DB\u5C42\u5206\u7C7B\uFF08\u672C\u4F53/\u80FD\u529B/\u89C4\u5219/\u4E8B\u4EF6\uFF09\uFF0C\u5224\u65AD\u4EA7\u51FA\u6807\u7B7E\uFF08article/video/tool/explore/none\uFF09\u3002\u8FD4\u56DEJSON\u3002`;
      const body = JSON.stringify({
        model: this.settings.deepseekModel,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `\u6587\u4EF6\uFF1A${file.name}
\u5185\u5BB9\uFF1A${content}` }
        ],
        temperature: 0.3,
        max_tokens: 2e3
      });
      const result = await new Promise((resolve, reject) => {
        const req = https.request({
          hostname: "api.deepseek.com",
          path: "/v1/chat/completions",
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${this.settings.deepseekApiKey}`,
            "Content-Length": Buffer.byteLength(body)
          }
        }, (res) => {
          let data = "";
          res.on("data", (chunk) => {
            data += chunk;
          });
          res.on("end", () => {
            resolve(`\u72B6\u6001=${res.statusCode} | \u6570\u636E=${data.slice(0, 500)}`);
          });
        });
        req.on("error", (e) => reject(e.message));
        req.write(body);
        req.end();
      });
      new import_obsidian5.Notice(`\u5B8C\u6574\u5206\u7C7B\u6D4B\u8BD5:
${result}`, 1e4);
    } catch (e) {
      new import_obsidian5.Notice(`\u6D4B\u8BD5\u5931\u8D25:
${e.message}`, 8e3);
    }
  }
  // ========== 文件变化处理 ==========
  onFileChange(file) {
    if (!this.settings.enabled || !this.settings.deepseekApiKey)
      return;
    if (isInCaptureDir(file.path))
      return;
    if (!isInDailyInputDir(file.path))
      return;
    const now = Date.now();
    this.pendingChanges.set(file.path, now);
    if (this.debounceTimer !== null) {
      window.clearTimeout(this.debounceTimer);
    }
    this.debounceTimer = window.setTimeout(async () => {
      const toProcess = [];
      for (const [path3, time] of this.pendingChanges) {
        if (Date.now() - time >= 2500) {
          toProcess.push(path3);
        }
      }
      this.pendingChanges.clear();
      for (const path3 of toProcess) {
        await this.processFile(path3);
      }
    }, 3e3);
  }
  /** 处理单个文件（走 AI 分类） */
  async processFile(filePath) {
    if (this.processedFiles.has(filePath))
      return;
    const file = this.app.vault.getAbstractFileByPath((0, import_obsidian5.normalizePath)(filePath));
    if (!(file instanceof import_obsidian5.TFile))
      return;
    try {
      this.engineStatus = "running";
      const content = await this.app.vault.read(file);
      if (!content.trim())
        return;
      const fileName = file.name;
      const result = await classifyContent(
        this.settings.deepseekApiKey,
        content,
        fileName,
        this.settings.deepseekModel
      );
      const itemId = `yy-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
      const pendingItems = await readPendingItems(this.app.vault);
      const newItem = {
        id: itemId,
        sourceFile: filePath,
        title: result.title,
        summary: result.summary,
        classification: {
          ontology: result.ontology,
          ability: result.ability,
          rule: result.rule,
          event: result.event,
          rationale: result.rationale
        },
        suggestedTag: result.tag,
        status: "pending",
        createdAt: (/* @__PURE__ */ new Date()).toISOString()
      };
      pendingItems.unshift(newItem);
      await writePendingItems(this.app.vault, pendingItems);
      await appendToClassifyLog(this.app.vault, {
        id: itemId,
        sourceFile: filePath,
        title: result.title,
        classification: {
          ontology: result.ontology,
          ability: result.ability,
          rule: result.rule,
          event: result.event,
          rationale: result.rationale
        },
        tag: result.tag,
        timestamp: (/* @__PURE__ */ new Date()).toISOString()
      });
      this.processedFiles.add(filePath);
      await this.saveProcessedState();
      new import_obsidian5.Notice(`\u5143\u6F14\u5F15\u64CE: \u5DF2\u5206\u7C7B\u300C${result.title}\u300D\u2192 ${result.tag}`);
      this.refreshApprovalView();
    } catch (e) {
      this.engineStatus = "error";
      const errMsg = e.message || String(e);
      const errStack = e.stack || "";
      console.error("\u5143\u6F14\u5F15\u64CE\u9519\u8BEF:", filePath, errMsg, errStack);
      new import_obsidian5.Notice(`\u5143\u6F14\u5F15\u64CE: \u5206\u7C7B\u5931\u8D25 \u2014 ${errMsg}`, 1e4);
    }
  }
  /** 处理所有未分类的日输入文件 */
  async processExistingFiles() {
    if (!this.settings.enabled || !this.settings.deepseekApiKey) {
      new import_obsidian5.Notice("\u5143\u6F14\u5F15\u64CE: \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Key");
      return;
    }
    const inputDir = (0, import_obsidian5.normalizePath)(DAILY_INPUT_DIR);
    if (!await this.app.vault.adapter.exists(inputDir)) {
      return;
    }
    const files = this.app.vault.getFiles().filter((f) => {
      return isInDailyInputDir(f.path) && !this.processedFiles.has(f.path);
    });
    if (files.length === 0)
      return;
    new import_obsidian5.Notice(`\u5143\u6F14\u5F15\u64CE: \u6B63\u5728\u5206\u7C7B ${files.length} \u4E2A\u6587\u4EF6...`);
    for (const file of files) {
      await this.processFile(file.path);
      await new Promise((r) => setTimeout(r, 500));
    }
  }
  // ========== Flomo 同步管理 ==========
  async startFlomoSync() {
    try {
      const resp = await fetch("http://127.0.0.1:8765/api/flomo/sync", { method: "POST" });
      if (resp.ok) {
        new import_obsidian5.Notice("Flomo \u540C\u6B65\u5DF2\u542F\u7528\uFF08\u5F15\u64CE\u540E\u53F0\u5B9A\u65F6\u8FD0\u884C\uFF09");
      }
    } catch (e) {
      new import_obsidian5.Notice("Flomo \u540C\u6B65\uFF1A\u5F15\u64CE\u672A\u8FD0\u884C\uFF0C\u4EC5\u76D1\u63A7\u6355\u83B7\u76EE\u5F55");
    }
    this.startFlomoCaptureWatch();
  }
  stopFlomoSync() {
    if (this.flomoCheckTimer !== null) {
      window.clearInterval(this.flomoCheckTimer);
      this.flomoCheckTimer = null;
    }
    new import_obsidian5.Notice("Flomo \u540C\u6B65\u5DF2\u505C\u7528");
  }
  async triggerFlomoSync() {
    try {
      const resp = await fetch("http://127.0.0.1:8765/api/flomo/sync", { method: "POST" });
      if (resp.ok) {
        const data = await resp.json();
        new import_obsidian5.Notice(`Flomo \u540C\u6B65\u5B8C\u6210: \u5BFC\u5165 ${data.imported || 0} \u6761`);
      } else {
        new import_obsidian5.Notice("Flomo \u540C\u6B65\u5931\u8D25: \u5F15\u64CE\u672A\u8FD0\u884C\uFF1F");
      }
    } catch (e) {
      new import_obsidian5.Notice("Flomo \u540C\u6B65\u5931\u8D25: \u65E0\u6CD5\u8FDE\u63A5\u5F15\u64CE");
    }
  }
  // ========== 捕获目录监控 ==========
  startFlomoCaptureWatch() {
    if (this.flomoCheckTimer !== null) {
      window.clearInterval(this.flomoCheckTimer);
    }
    this.flomoCheckTimer = window.setInterval(() => {
      this.checkCaptureDir();
    }, 3e4);
  }
  async checkCaptureDir() {
    const captureDir = (0, import_obsidian5.normalizePath)(CAPTURE_DIR);
    if (!await this.app.vault.adapter.exists(captureDir)) {
      return;
    }
    const files = this.app.vault.getFiles().filter(
      (f) => isInCaptureDir(f.path) && !this.declinedFiles.has(f.path)
    );
    for (const file of files) {
      await this.promptFlomoConfirm(file);
      return;
    }
  }
  async promptFlomoConfirm(file) {
    const content = await this.app.vault.read(file);
    const title = file.name.replace(/\.md$/, "");
    return new Promise((resolve) => {
      const modal = new FlomoConfirmModal(
        this.app,
        this,
        file.path,
        title,
        content.replace(/^---[\s\S]*?---\n/, ""),
        // 去掉 frontmatter
        async () => {
          const targetDir = (0, import_obsidian5.normalizePath)(DAILY_INPUT_DIR);
          const result = await moveFile(this.app.vault, file.path, targetDir);
          if (result) {
            new import_obsidian5.Notice(`\u5DF2\u79FB\u5165\u65E5\u8F93\u5165: ${title}`);
            await this.processFile(result);
          } else {
            new import_obsidian5.Notice(`\u79FB\u52A8\u5931\u8D25: ${title}`, 5e3);
          }
          resolve();
        },
        () => {
          this.declinedFiles.add(file.path);
          this.saveDeclinedState();
          new import_obsidian5.Notice(`\u7559\u5728\u6355\u83B7: ${title}`);
          resolve();
        }
      );
      modal.open();
    });
  }
  // ========== Declined 持久化 ==========
  async loadDeclinedState() {
    const data = await this.loadData();
    if (data == null ? void 0 : data.declinedFiles) {
      this.declinedFiles = new Set(data.declinedFiles);
    }
  }
  async saveDeclinedState() {
    const data = await this.loadData() || {};
    data.declinedFiles = Array.from(this.declinedFiles);
    await this.saveData(data);
  }
  // ========== 视图管理 ==========
  async openApprovalView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(APPROVAL_VIEW_TYPE).first();
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: APPROVAL_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  refreshApprovalView() {
    const leaves = this.app.workspace.getLeavesOfType(APPROVAL_VIEW_TYPE);
    for (const leaf of leaves) {
      if (leaf.view instanceof ApprovalView) {
        leaf.view.render();
      }
    }
  }
};
